apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: fromsoft-tools-infra
build:
  artifacts:
    - image: fstools.azurecr.io/fstools-build
      platforms: ["linux/amd64"]
      docker:
        dockerfile: actions-runner/Dockerfile
  local: {}
manifests:
  rawYaml: 
    - actions-runner/test-data-storage.pvc.yml

deploy:
  helm:
    releases:
    - name: arc-runner-set
      remoteChart: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
      version: "0.8.2"
      namespace: github-arc-runners
      upgradeOnChange: true
      createNamespace: true
      setValueTemplates:
        template:
          spec:
            containers:
              - name: runner
                image: "{{.IMAGE_REPO_fstools_azurecr_io_fstools_build}}:{{.IMAGE_TAG_fstools_azurecr_io_fstools_build}}@{{.IMAGE_DIGEST_fstools_azurecr_io_fstools_build}}"
      setValues:
        githubConfigSecret: gh-app-token
        githubConfigUrl: https://github.com/garyttierney/fstools-rs
        template:
          spec:
            tolerations:
            - key: "kubernetes.azure.com/scalesetpriority"
              operator: "Equal"
              value: "spot"
              effect: "NoSchedule"
            - key: "sku"
              operator: "Equal"
              value: "workloads"
              effect: "NoSchedule"
            nodeSelector:
              usage: workloads

            containers:
            - name: runner
              imagePullPolicy: Always
              command: ["/home/runner/run.sh"]
              env:
              - name: ACTIONS_RUNNER_POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              volumeMounts:
                - mountPath: "/opt/test-data"
                  name: test-data
                  readOnly: true
            volumes:
              - name: test-data
                persistentVolumeClaim:
                  claimName: fstools-test-data