apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    namespace: github-arc-runners
    name: fstools-test-data
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 100Gi